import { StyleSheet } from "react-native";

export const estudiantesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#eaf1ff",
    padding: 16,
  },
  title: {
    fontSize: 30,
    fontWeight: "900",
    color: "#0b132b",
    marginTop: 10,
    letterSpacing: 0.3,
  },
  subtitle: {
    fontSize: 15,
    color: "#4f5d75",
    marginTop: 6,
    marginBottom: 18,
    fontWeight: "500",
  },
  searchInput: {
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#c7d2fe",
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    fontSize: 15,
    color: "#0f172a",
    shadowColor: "#1e3a8a",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  openModalButton: {
    backgroundColor: "#4f46e5",
    paddingVertical: 14,
    borderRadius: 16,
    marginBottom: 18,
    shadowColor: "#312e81",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  openModalButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "800",
    fontSize: 16,
    letterSpacing: 0.3,
  },
  studentCard: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#dbeafe",
    shadowColor: "#1e293b",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  studentName: {
    fontSize: 19,
    fontWeight: "900",
    color: "#0b132b",
    marginBottom: 8,
    letterSpacing: 0.2,
  },
  studentText: {
    fontSize: 14,
    color: "#475569",
    marginBottom: 4,
    lineHeight: 20,
  },
  deleteButton: {
  flex: 1,
  backgroundColor: "#ef4444",
  paddingVertical: 11,
  borderRadius: 14,
  },
  deleteButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  emptyText: {
    textAlign: "center",
    color: "#64748b",
    marginTop: 28,
    fontSize: 15,
    fontWeight: "500",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    justifyContent: "center",
    padding: 22,
  },
  modalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#dbeafe",
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 16,
    color: "#0b132b",
    letterSpacing: 0.2,
  },
  input: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginBottom: 12,
    backgroundColor: "#f8fafc",
    fontSize: 15,
    color: "#0f172a",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  addButton: {
    flex: 1,
    backgroundColor: "#10b981",
    paddingVertical: 14,
    borderRadius: 14,
  },
  addButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#64748b",
    paddingVertical: 14,
    borderRadius: 14,
  },
  cancelButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  cardActionsRow: {
  flexDirection: "row",
  gap: 10,
  marginTop: 14,
},
editButton: {
  flex: 1,
  backgroundColor: "#f59e0b",
  paddingVertical: 11,
  borderRadius: 14,
},
editButtonText: {
  color: "#ffffff",
  textAlign: "center",
  fontWeight: "800",
  letterSpacing: 0.2,
},
});