import { StyleSheet } from "react-native";

export const programasStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#eaf1ff",
    padding: 16,
  },
  title: {
    fontSize: 31,
    fontWeight: "900",
    color: "#0b132b",
    marginTop: 10,
    letterSpacing: 0.3,
  },
  subtitle: {
    fontSize: 15,
    color: "#4f5d75",
    marginTop: 6,
    marginBottom: 18,
    fontWeight: "500",
  },
  addButton: {
    backgroundColor: "#2563eb",
    paddingVertical: 15,
    borderRadius: 16,
    marginBottom: 18,
    shadowColor: "#1d4ed8",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  addButtonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "800",
    fontSize: 16,
    letterSpacing: 0.3,
  },
  card: {
    backgroundColor: "#ffffff",
    borderRadius: 22,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#dbeafe",
    shadowColor: "#1e293b",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  programName: {
    fontSize: 20,
    fontWeight: "900",
    color: "#0b132b",
    letterSpacing: 0.2,
  },
  programCode: {
    marginTop: 7,
    fontSize: 14,
    color: "#4338ca",
    fontWeight: "700",
  },
  programCount: {
    marginTop: 6,
    fontSize: 14,
    color: "#334155",
    fontWeight: "600",
  },
  actionsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 16,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: "#4f46e5",
    paddingVertical: 13,
    borderRadius: 14,
  },
  deleteButton: {
    flex: 1,
    backgroundColor: "#ef4444",
    paddingVertical: 13,
    borderRadius: 14,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "#64748b",
    paddingVertical: 13,
    borderRadius: 14,
  },
  buttonText: {
    color: "#ffffff",
    textAlign: "center",
    fontWeight: "800",
    letterSpacing: 0.2,
  },
  emptyText: {
    textAlign: "center",
    color: "#64748b",
    marginTop: 30,
    fontSize: 15,
    fontWeight: "500",
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.45)",
    justifyContent: "center",
    padding: 22,
  },
  modalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#dbeafe",
    shadowColor: "#0f172a",
    shadowOpacity: 0.12,
    shadowRadius: 14,
    elevation: 6,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 16,
    color: "#0b132b",
    letterSpacing: 0.2,
  },
  input: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
    marginBottom: 12,
    backgroundColor: "#f8fafc",
    fontSize: 15,
    color: "#0f172a",
  },
  modalActions: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  editButton: {
  flex: 1,
  backgroundColor: "#f59e0b",
  paddingVertical: 13,
  borderRadius: 14,
},
});